sudo: false
language: node_js
node_js:
  - "8"
install:
  - npm install -g yaspeller
  - npm install -g markdown-link-check
  - npm install -g markdownlint-cli
script: 
  - yaspeller -e ".md" ./
  - find . -name \*.md -exec markdown-link-check {} \;
  - stylecheck
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules
