sudo: false
language: node_js
node_js:
  - "8"
install:
  - wget https://raw.githubusercontent.com/axibase/atsd/master/.travis-functions.sh && source .travis-functions.sh
  - install_checkers
script:
  - print_modified_markdown_files
  - spellcheck --single
  - linkcheck
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules
notifications:
  webhooks: https://apps.axibase.com/api/v1/messages/wk-travis-ci/travis-ci